name: Keep Backend Awake

on:
  schedule:
    - cron: "*/50 * * * *"
  workflow_dispatch:

jobs:
  ping-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Curl backend root endpoint
        run: |
          curl --fail --silent --show-error "${{ secrets.BACKEND_URL }}" || exit 1
